### ISSUE TITLE
The answers of the questionnaires are revealed

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/mooc-grader#103]
This happens in a very specific case. If we set `submissions` equal to 1 and set `reveal-model-at-max-submissions` equals to True, students can get the answers before submitting the questionnaire.

The student can submit the questionnaire without checking any of the answers, then Aplus will provide the students with the feedback that includes the correct answers, then students can select the correct answers and get all the points. 

*Test Case*
```rst
.. questionnaire:: Testing 20
  :title: Getting answers
  :submissions: 1
  :reveal-model-at-max-submissions: True

  .. pick-one:: 10
    :required:

    **Modifiers used in this question:** ``required``.

    When :math:`(x + 1)^3 = 27`, what is :math:`x`?

    a. 9
    *b. 2
    c. 3

    a § Not quite. Remember the cube root.
    b § Correct!
    c § Rather close. Remember that you can add or subtract the same number to both sides of the equation.

  .. pick-any:: 10
    :required:

    **Modifiers used in this question:** ``required``.

    When :math:`(x + 1)^2 = 16`, what is :math:`x`?

    a. 4
    *b. an integer
    *c. 3
    d. an irrational number
    e. -3
    *f. -5

    a § Rather close. Remember that you can add or subtract the same number to both sides of the equation.
    b § Correct!
    c § Correct!
    d § No. This equation has a nice and easy solution.
    e § Remember that :math:`x^2 = q \leftrightarrow x = \pm \sqrt{q}`
    f § Correct!
```
**Check the following video**

https://user-images.githubusercontent.com/10437475/107668748-accf6080-6c99-11eb-88d5-e540cb46567c.mp4

**Comment by skulonen** [comment]
I actually can't reproduce this issue directly because the browser refuses to submit the form without all `required` fields filled in. Both Firefox and Chrome behave like this.

![image](https://user-images.githubusercontent.com/28843787/118781986-4eb4a980-b896-11eb-9e48-bc82ea5c77e6.png)

However, if i use inspect element to remove the `required` attributes from the form elements, I can submit the form and get the correct answers like in the video. That means the system can still be exploited if the user knows about this issue (e.g. by reading this comment). I'll go ahead and fix this.
