### ISSUE TITLE
Support rewriting of static_dir urls

### ISSUE THREAD

**Issue by piehei** [apluslms/mooc-grader#31]
Currently if you try to show an image (or link to a downloadable file or whatever) in an erercise_config.yaml based exercise instructions, you have to know the hard-coded *actual* url where the image resides at the production server, and the image file of course has to be copied (or symlinked to) the static directory of the course. This affects all the cases where you want to link to some file in the course static dir.

If you cannot completely adopt the RST workflow, you have this problem.

This comes with problems:
1. when you run local dev environment (course-templates), mooc-grader serves your course from /default which makes your static dir /static/default
2. when you deploy your course to production, your course key changes from default to something, thus breaking links that worked in local dev environment
3. none of the usual ways of linking work, you cannot do "./static/blah.jpg", "/static/blah.jpg", "../static/blah.jpg" etc. because the static path depends *solely* on the dir where the course files reside on the production server

Or am I missing something? (Totally could be!!!)

One way to solve:
rewrite all urls in exercise_config.yaml so that they point to the correct static path on the server, eg. if you put "/static/my_file.png" in some exercise_config.yaml, it would be rewritten to "/static/COURSE_KEY/my_file.png"; this solution takes a couple of lines of code only and I have it ready since I played around with it a bit (I implemented this in util/templates.py).

What do you think?

:)

**Comment by raphendyr** [comment]
Wait for roman

**Comment by Mankro** [comment]
This issue is old and the handling of links has changed a little over the years, though the problem presented in this issue is still relevant.

A-plus-rst-tools makes some changes to the URLs so that they work in the A+ frontend. This affects exercise instructions HTML too. Manually written HTML in exercise config.yaml files may use the same format that a-plus-rst-tools output. For example, an image tag:

`<img alt="Aplus logo" data-aplus-path="/static/{course}" src="../_images/apluslogo.png"/>`




The new gitmanager service in A+ v1.12 defines `STATIC_CONTENT_HOST` for the build container. A-plus-rst-tools uses it in the `static_host` conf.py setting. Custom build scripts could also use the environment variable.
https://github.com/apluslms/gitmanager/blob/912a7fceff8b232445bbe6cb6d5791f2f4daccf3/builder/builder.py#L112
The value of STATIC_CONTENT_HOST is like:
`https://gitmanager.cs.aalto.fi/static/<coursekey>`
where `<coursekey>` is the correct course key.
