### ISSUE TITLE
The default message 'Multiple choices are selectable' is not quite accuarate

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/mooc-grader#93]
The feedback message 'Multiple choices are selectable'  is added to the questionnaires when the students select one incorrect answer in the multiple-choice questionnaire. But, that feedback is misleading because nothing restricts teachers from having only one right answer. Therefore, this message may be confusing and suggest that students select more than one checkbox. The following image shows a use case.

![image](https://user-images.githubusercontent.com/10437475/102591164-3f300980-411a-11eb-9410-4d6b6cc70aa8.png)

I think that the following code is causing the issue.
https://github.com/apluslms/mooc-grader/blob/db5135b6e18ec0a8e62cac4b763ffb4a421f4f79/access/types/forms.py#L643

**Comment by jaguarfi** [comment]
This is working fine. It was an error in the testing.

**Comment by Mankro** [comment]
I have never liked that message. It should be obvious that multiple checkboxes can be selected when the question has checkboxes instead of radio buttons. In addition, the hint reveals that the correct answer contains more than one checkbox, which does not make sense to me. The hint could be displayed all the time if we really think that the student does not know how checkboxes work, but I would prefer to remove the whole hint "Multiple choices are selectable".

**Comment by jsorva** [comment]
I originally requested that feature, I think. I'd prefer that it stays — at least as an optional thing that I can switch on. In my materials, that hint doesn't reveal anything unintended, but I can see how it might be superfluous or even undesirable in some other contexts.

(I’d change “Multiple choices are selectable” to the more direct “You may choose multiple options.”, though.)

**Comment by Mankro** [comment]
I added the need for toggling this hint on or off in the new issue #102.
